### ISSUE TITLE
Internal error when using custom NER model

### ISSUE THREAD

**Issue by rafikg** [googleapis/python-automl#126]
I trained a custom model for named entity recognition using Automl service on GCP. Here is my code to run it using python:

```
from google.cloud import automl

# TODO(developer): Uncomment and set the following variables
# project_id = "YOUR_PROJECT_ID"
# model_id = "YOUR_MODEL_ID"
# content = "text to predict"

prediction_client = automl.PredictionServiceClient()

# Get the full path of the model.
model_full_id = automl.AutoMlClient.model_path(
    project_id, "us-central1", model_id
)


text_snippet = automl.TextSnippet(
    content=text_content, mime_type="text/plain"
)
payload = automl.ExamplePayload(text_snippet=text_snippet)

response = prediction_client.predict(name=model_full_id, payload=payload)

for annotation_payload in response.payload:
    print(
        "Text Extract Entity Types: {}".format(
            annotation_payload.display_name
        )
    )
    print(
        "Text Score: {}".format(annotation_payload.text_extraction.score)
    )
    text_segment = annotation_payload.text_extraction.text_segment
    print("Text Extract Entity Content: {}".format(text_segment.content))
    print("Text Start Offset: {}".format(text_segment.start_offset))
    print("Text End Offset: {}".format(text_segment.end_offset))
```

I get this internal error in `predict()` function:

```
Traceback (most recent call last):
  File "/opt/conda/envs/myenv/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/conda/envs/myenv/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/envs/myenv/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Internal error encountered."
	debug_error_string = "{"created":"@1258996669854.77788844","description":"Error received from peer ipv4:1.2.3.4","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Internal error encountered.","grpc_status":13}"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxxx/project/main/demo.py", line 117, in <module>
    print(get_prediction(content=text_content, model_name=model_full_id))
  File "/home/xxxx/project/main/demo.py", line 114, in get_prediction
    request = prediction_client.predict(name=model_name, payload=payload)
  File "/opt/conda/envs/myenv/lib/python3.6/site-packages/google/cloud/automl_v1/services/prediction_service/client.py", line 413, in predict
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/opt/conda/envs/myenv/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/myenv/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.

```

Can someone from GCP explain the source of error and how to fix it?

**Comment by rafikg** [comment]
@jskeet Could please check the problem. I have to stop charge my client for a false call. I have created a service account before start training the model and give myself `Automl admin` role. Training is going very well. The problem is when I try to call the model using python script

**Comment by jskeet** [comment]
@rafikg: I work on the .NET client libraries, which is where you filed the issue to start with. I'm afraid I don't know anything about the Python client libraries, or the AutoML API, so I'm unable to help you.

**Comment by rafikg** [comment]
I resolved the problem. The error is in the `model_full_id = automl.AutoMlClient.model_path(
    project_id, "us-central1", model_id
)`

in the `project_id` parameter, we have to put the `project number` not the project ID. It is a waste of time and too confused

**Comment by munkhuushmgl** [comment]
Hello @rafikg 

I am looking into this issue.

**Comment by munkhuushmgl** [comment]
I have used my project with your. code snippet provided
![image](https://user-images.githubusercontent.com/45373284/107283471-4d5f1f80-6a11-11eb-86af-0031e3bd2938.png)

It is working as intended.

```
def predict(project_id, model_id, content):
  from google.cloud import automl

  # TODO(developer): Uncomment and set the following variables
  # project_id = "YOUR_PROJECT_ID"
  # model_id = "YOUR_MODEL_ID"
  # content = "text to predict"

  prediction_client = automl.PredictionServiceClient()

  # Get the full path of the model.
  model_full_id = automl.AutoMlClient.model_path(
      project_id, "us-central1", model_id
  )


  text_snippet = automl.TextSnippet(
      content=content, mime_type="text/plain"
  )
  payload = automl.ExamplePayload(text_snippet=text_snippet)

  response = prediction_client.predict(name=model_full_id, payload=payload)

  for annotation_payload in response.payload:
      print(
          "Text Extract Entity Types: {}".format(
              annotation_payload.display_name
          )
      )
      print(
          "Text Score: {}".format(annotation_payload.text_extraction.score)
      )
      text_segment = annotation_payload.text_extraction.text_segment
      print("Text Extract Entity Content: {}".format(text_segment.content))
      print("Text Start Offset: {}".format(text_segment.start_offset))
      print("Text End Offset: {}".format(text_segment.end_offset))

text = "Constitutional mutations in the WT1 gene in patients with Denys-Drash syndrome."
predict("java-docs-samples-testing", "TEN000000000000", text)
```

what do you mean by `project_id`?

**Comment by rafikg** [comment]
@munkhuushmgl  on google cloud screen, there is `project_id` and `project number`. We should use `project number` instead of `project_id`.

**Comment by munkhuushmgl** [comment]
Hey @rafikg Can you create public traking issue on GCP as a feature request?
