### ISSUE TITLE
2.0.0 version, grpc google.api_core.exceptions.ResourceExhausted

### ISSUE THREAD

**Issue by jaimemm-g** [googleapis/python-automl#76]
Hi,

It seems v2.0.0 introduced changes that makes calls working on former v1.0.1, to be broken due to grpc receive message limit.

#### Environment details

  - Linux/GCP Cloud Functions
  - Python version: 3.7 & 3.8
  - pip version: 20.1.1
  - `google-cloud-automl` version: 2.0.0

#### Steps to reproduce

1. Execute de code

#### Code example

import traceback 
from google.cloud import automl_v1beta1

try:
  client_options = {'api_endpoint': model_api_endpoint} 
  client = automl_v1beta1.TablesClient(project=model_gcp_project, region=model_region, client_options=client_options)
  model = client.get_model(model_display_name=model_name)
except:
      traceback.print_exc()

#### Stack trace

Traceback (most recent call last):
  File "/xxx/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/xxxx/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/xxx/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (6971181 vs. 4194304)"
	debug_error_string = "{"created":"@1600678917.115592138","description":"Received message larger than max (6971181 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":189,"grpc_status":8}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 220, in get_model_status
    model = client.get_model(model_display_name=model_name)
  File "/xxx/lib/python3.8/site-packages/google/cloud/automl_v1beta1/services/tables/tables_client.py", line 2588, in get_model
    self.list_models(project=project, region=region),
  File "/xxx/lib/python3.8/site-packages/google/cloud/automl_v1beta1/services/tables/tables_client.py", line 2143, in list_models
    return self.auto_ml_client.list_models(request=request, **method_kwargs)
  File "/xxx/lib/python3.8/site-packages/google/cloud/automl_v1beta1/services/auto_ml/client.py", line 1777, in list_models
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/xxx/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/xxx/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/xxx/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/xxx/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ResourceExhausted: 429 Received message larger than max (6971181 vs. 4194304)

**Comment by busunkim96** [comment]
We didn't make changes to the gRPC calls themselves between the two library versions. Can you confirm you only see the issue with the 2.0.0 even when you fetch the same model?

**Comment by busunkim96** [comment]
Closing due to lack of activity
